title: security portfolio + blog
description: by Nicholas Coleman
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

# Navigation
header_pages:
  - index.md
  - blog.md

baseurl: "/security.github.io"
url: "https://nicoleman0.github.io"

# Configure blog
permalink: /blog/:year/:month/:day/:title/
