title: "Cybersecurity Portfolio - Nicholas Coleman"
description: "Showcasing cybersecurity projects by Nicholas Coleman."
remote_theme: mmistakes/minimal-mistakes
show_downloads: true
google_analytics: 

# Site settings
baseurl: ""  # Leave empty if using GitHub Pages with default username.github.io domain
url: "https://yourusername.github.io"  # Replace with your actual GitHub Pages URL

# Plugins required by Minimal Mistakes
plugins:
  - jekyll-include-cache

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/

# Include extra directories
include:
  - _pages
